### PR TITLE
Add business type to Customer struct

### PR DESCRIPTION
**Pull request by sachsry**
Add business type to Customer struct

### CODE REVIEW

**Review by kolanos — APPROVED** [review]

**Comment by kolanos** [comment]
Thanks @sachsry.

**Comment by sachsry** [comment]
np thanks for the quick review and merge @kolanos

**Comment by sachsry** [comment]
how does the code get published [here](https://pkg.go.dev/github.com/kolanos/dwolla-v2-go)?

**Comment by sachsry** [comment]
@kolanos can you publish the latest for this? Not sure if there's another way to import it. Go mod automatically grabs what's published https://pkg.go.dev/github.com/kolanos/dwolla-v2-go

**Comment by kolanos** [comment]
@sachsry `go get -u github.com/kolanos/dwolla-v2-go` will get you the latest. Also your change is reflected in the link you provided.

**Comment by sachsry** [comment]
@kolanos Hmm.. maybe I'm looking at the wrong place somehow but seems like it's not there? https://github.com/kolanos/dwolla-v2-go/blob/2967e0eb9d6f/customer.go#L88

I can try updating and see

**Comment by kolanos** [comment]
It is in the `master` branch: https://github.com/kolanos/dwolla-v2-go/blob/master/customer.go#L89

I also just tagged a `v1.1.1` version.

**Comment by sachsry** [comment]
Thanks @kolanos was able to pull the latest version with the tagging and see the business type - appreciate your help

**Pull request merged**
